version: '3.8'

services:
  grpc_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - .:/app
    networks:
      - grpc_network

networks:
  grpc_network:
    external: true  # Use the external network created
